ALTER TABLE CMT_ELEMENT_TYPE
	ADD [TYPE] TINYINT NOT NULL CONSTRAINT DF_CMT_ELEMENT_TYPE DEFAULT(0)
GO

update CMT_ELEMENT_TYPE
set [TYPE] = 1
where NAME = 'LOV'


EXEC RegisterSchemaVersion '0.1.190618.00000.0'
