

CREATE TABLE [dbo].[CMT_VALUE_TAG](
	[OBJECT_ID] [uniqueidentifier] NOT NULL,
	[VALUE_ID] [uniqueidentifier] NOT NULL,
	[TYPE] [tinyint] NOT NULL,
	[SCHEMA_TAG] nvarchar(50) NULL,
	[TAG_ELEMENT_ID] [uniqueidentifier] NULL,
	[TAG_VALUE_ID] [uniqueidentifier] NULL,
	[CREATE_USER] [nvarchar](100) NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[CHANGE_USER] [nvarchar](100) NULL,
	[CHANGE_DATE] [datetime] NULL,

 CONSTRAINT [PK_CMT_VALUE_TAG] PRIMARY KEY CLUSTERED 
(
	[OBJECT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[CMT_VALUE_TAG] ADD  CONSTRAINT [DF_CMT_VALUE_TAG_OBJECT_ID]  DEFAULT (newsequentialid()) FOR [OBJECT_ID]
GO

ALTER TABLE [dbo].[CMT_VALUE_TAG] ADD  CONSTRAINT [DF_CMT_VALUE_TAG_TYPE]  DEFAULT ((0)) FOR [TYPE]
GO

ALTER TABLE [dbo].[CMT_VALUE_TAG] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO



ALTER TABLE [dbo].[CMT_VALUE_TAG]  WITH CHECK ADD  CONSTRAINT [FK_CMT_METADATA_ELEMENT_CMT_VALUE_TAG] FOREIGN KEY([TAG_ELEMENT_ID])
REFERENCES [dbo].[CMT_METADATA_ELEMENT] ([OBJECT_ID])
GO

ALTER TABLE [dbo].[CMT_VALUE_TAG] CHECK CONSTRAINT [FK_CMT_METADATA_ELEMENT_CMT_VALUE_TAG]
GO

ALTER TABLE [dbo].[CMT_VALUE_TAG]  WITH CHECK ADD  CONSTRAINT [FK_CMT_VALUE_CMT_VALUE_TAG] FOREIGN KEY([VALUE_ID])
REFERENCES [dbo].[CMT_VALUE] ([OBJECT_ID])
GO

ALTER TABLE [dbo].[CMT_VALUE_TAG] CHECK CONSTRAINT [FK_CMT_VALUE_CMT_VALUE_TAG]
GO

ALTER TABLE [dbo].[CMT_VALUE_TAG]  WITH CHECK ADD  CONSTRAINT [FK_CMT_VALUE2_CMT_VALUE_TAG] FOREIGN KEY([TAG_VALUE_ID])
REFERENCES [dbo].[CMT_VALUE] ([OBJECT_ID])
GO

ALTER TABLE [dbo].[CMT_VALUE_TAG] CHECK CONSTRAINT [FK_CMT_VALUE2_CMT_VALUE_TAG]
GO



EXEC RegisterSchemaVersion '0.1.190712.00000.0'