ALTER TABLE CMT_VALUE_TAG
	ADD COUNTRY_ID UNIQUEIDENTIFIER NULL CONSTRAINT FK_CMT_VALUE_TAG_CMT_COUNTRY FOREIGN KEY  REFERENCES CMT_COUNTRY(OBJECT_ID)
GO

exec RegisterSchemaVersion '0.1.190822.00000.0'

