ALTER TABLE CMT_VALUE_DETAIL
ADD ATTRIBUTE_ELEMENT_ID uniqueidentifier null


ALTER TABLE CMT_VALUE_DETAIL
ADD ATTRIBUTE_VALUE_ID  uniqueidentifier null



ALTER TABLE [dbo].[CMT_VALUE_DETAIL]  WITH CHECK ADD  CONSTRAINT [FK_CMT_METADATA_ELEMENT_CMT_VALUE_DETAIL] FOREIGN KEY(ATTRIBUTE_ELEMENT_ID)
REFERENCES [dbo].CMT_METADATA_ELEMENT ([OBJECT_ID])
GO

ALTER TABLE [dbo].[CMT_VALUE_DETAIL]  WITH CHECK ADD  CONSTRAINT [FK_CMT_VALUE2_CMT_VALUE_DETAIL] FOREIGN KEY([ATTRIBUTE_VALUE_ID])
REFERENCES [dbo].CMT_VALUE ([OBJECT_ID])
GO


ALTER TABLE [dbo].[CMT_VALUE_DETAIL]
ALTER COLUMN VALUE nvarchar(200) null


ALTER TABLE [dbo].[CMT_VALUE_DETAIL] DROP CONSTRAINT [AK_CMT_VALUE_DETAIL_VALUE_ID_COUNTRY_ID_EXTERNAL_ID]
GO