CREATE TABLE [dbo].[CMT_SETTING](
	[OBJECT_ID] [uniqueidentifier] NOT NULL,
	[NAME] [nvarchar](200) NOT NULL,
	[VALUE] [nvarchar](max) NOT NULL,
	[COUNTRY_ID] [uniqueidentifier] NULL,
	[CREATE_USER] [nvarchar](100) NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[CHANGE_USER] [nvarchar](100) NULL,
	[CHANGE_DATE] [datetime] NULL,
 CONSTRAINT [PK_CMT_SETTING_OBJECT_ID] PRIMARY KEY CLUSTERED 
(
	[OBJECT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[CMT_SETTING] ADD  CONSTRAINT [DF_CMT_SETTING_OBJECT_ID]  DEFAULT (newid()) FOR [OBJECT_ID]
GO

ALTER TABLE [dbo].[CMT_SETTING]  WITH CHECK ADD  CONSTRAINT [FK_CMT_COUNTRY_CMT_SETTING] FOREIGN KEY([COUNTRY_ID])
REFERENCES [dbo].[CMT_COUNTRY] ([OBJECT_ID])
GO

ALTER TABLE [dbo].[CMT_SETTING] CHECK CONSTRAINT [FK_CMT_COUNTRY_CMT_SETTING]
GO

ALTER TABLE [dbo].[CMT_SETTING] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO

exec RegisterSchemaVersion '0.1.200929.00000.0'
GO



