CREATE TABLE dbo.SEC_USER_COUNTRY(
	OBJECT_ID UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_SEC_USER_COUNTRY_OBJECT_ID DEFAULT(NEWSEQUENTIALID()),
	USER_ID UNIQUEIDENTIFIER NOT NULL,
	COUNTRY_ID UNIQUEIDENTIFIER NOT NULL,
	CREATE_USER NVARCHAR(100) NOT NULL,
	CREATE_DATE DATETIME NOT NULL CONSTRAINT DF_SEC_USER_COUNTRY_CREATE_DATE DEFAULT(GETDATE()),
	CHANGE_USER NVARCHAR(100) NULL,
	CHANGE_DATE DATETIME NULL
)
GO

ALTER TABLE dbo.SEC_USER_COUNTRY
	ADD CONSTRAINT PK_SEC_USER_COUNTRY PRIMARY KEY(OBJECT_ID),
	CONSTRAINT FK_SEC_USER_COUNTRY_SEC_USER FOREIGN KEY(USER_ID) REFERENCES SEC_USER(OBJECT_ID),
	CONSTRAINT FK_SEC_USER_COUNTRY_CMT_COUNTRY FOREIGN KEY(COUNTRY_ID) REFERENCES CMT_COUNTRY(OBJECT_ID)
GO

exec RegisterSchemaVersion '0.1.190524.00000.0'
GO
