
































// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>

using CMT.Common.Interfaces;

namespace CMT.DL
{
    #region auto-generated code

    public partial class Campaign : IDbObject, IAuditableObject { }

    public partial class CampaignValue : IDbObject, IAuditableObject { }

    public partial class Country : IDbObject, IAuditableObject { }

    public partial class DistinctRow : IDbObject, IAuditableObject { }

    public partial class ElementType : IDbObject, IAuditableObject { }

    public partial class Import : IDbObject, IAuditableObject { }

    public partial class MetadataElement : IDbObject, IAuditableObject { }

    public partial class MetadataSchema : IDbObject, IAuditableObject { }

    public partial class MetadataSchemaElement : IDbObject, IAuditableObject { }

    public partial class MetadataGroup : IDbObject, IAuditableObject { }

    public partial class SourceTable : IDbObject, IAuditableObject { }

    public partial class SourceValue : IDbObject, IAuditableObject { }

    public partial class Value : IDbObject, IAuditableObject { }

    public partial class ValueDetail : IDbObject, IAuditableObject { }

    public partial class ValueList : IDbObject, IAuditableObject { }

    public partial class CampaignImport : IDbObject { }

    public partial class ViewElement : IDbObject { }

    public partial class Channel : IDbObject, IAuditableObject { }

    public partial class ViewCampaign : IDbObject, IAuditableObject { }

    public partial class ViewMetadataElementTree : IDbObject { }

    public partial class ValueListLevel : IDbObject, IAuditableObject { }

    public partial class Application : IDbObject, IAuditableObject { }

    public partial class DistinctRowGrouping : IDbObject, IAuditableObject { }

    public partial class ViewValueTree : IDbObject, IAuditableObject { }

    public partial class Role : IDbObject, IAuditableObject { }

    public partial class User : IDbObject, IAuditableObject { }

    public partial class UserClaim : IDbObject { }

    public partial class UserLogin : IDbObject { }

    public partial class UserRole : IDbObject { }

    public partial class BrandImportHistory : IDbObject { }

    public partial class DataRange : IDbObject, IAuditableObject { }

    public partial class SchemaTag : IDbObject, IAuditableObject { }

    public partial class UserCountry : IDbObject, IAuditableObject { }


    public partial class ColumnHeader : IDbIntObject, IAuditableObject { }


    public partial class ValueTag : IDbObject, IAuditableObject { }

    public partial class Setting : IDbObject, IAuditableObject { }
    #endregion
}
